/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author jeana
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPanePrincipal = new javax.swing.JScrollPane();
        jPanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPaneCadastro = new javax.swing.JScrollPane();
        jTabbedPaneCadastro = new javax.swing.JTabbedPane();
        jScrollPaneDiretorCad = new javax.swing.JScrollPane();
        jPanelCadDiretor = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cxNomeDirCad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btCadDir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cxCpfDirCad = new javax.swing.JTextField();
        jScrollPaneProfessorCad = new javax.swing.JScrollPane();
        jPanelCadProfessor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cxNomeProfCad = new javax.swing.JTextField();
        btCadProf = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cxCpfProfCad = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cxDisciplinaProfCad = new javax.swing.JTextField();
        jScrollPaneAlunoCad = new javax.swing.JScrollPane();
        jPanelAluno = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cxNomeAlunoCad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cxRaAlunoCad = new javax.swing.JTextField();
        btCadAluno = new javax.swing.JButton();
        cxTurmaAlunoCad1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPaneConsulta = new javax.swing.JScrollPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPaneDiretorCons = new javax.swing.JScrollPane();
        jPanelCadDiretor1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cxNomeDirCons = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btConsDir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cxCpfDirCons = new javax.swing.JTextField();
        btAlterarDir = new javax.swing.JButton();
        btDeletarDir = new javax.swing.JButton();
        btListarDir = new javax.swing.JButton();
        jScrollPaneProfessorCons = new javax.swing.JScrollPane();
        jPanelCadDiretor2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cxNomeProfessorCons = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btConsProfessor = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cxCpfProfessorCons = new javax.swing.JTextField();
        btAlterarProfessor = new javax.swing.JButton();
        btDeletarProfessor = new javax.swing.JButton();
        btListarProfessor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cxDisciplinaProfessorCons = new javax.swing.JTextField();
        jScrollPaneAlunoCons = new javax.swing.JScrollPane();
        jPanelCadDiretor3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        cxNomeAlunoCons = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btConsAluno = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        cxRaAlunoCons = new javax.swing.JTextField();
        btAlterarAluno = new javax.swing.JButton();
        btDeletarAluno = new javax.swing.JButton();
        btListarAlunos = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        cxTurmaAlunoCons = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Iniciar = new javax.swing.JMenu();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenuItemSalvar = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 153));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jScrollPanePrincipal.setBackground(new java.awt.Color(255, 102, 102));

        jPanelPrincipal.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GERENCIADOR  ESCOLA UNITED");
        jPanelPrincipal.add(jLabel1);

        jScrollPanePrincipal.setViewportView(jPanelPrincipal);

        jTabbedPane1.addTab("Principal", jScrollPanePrincipal);

        jLabel5.setText("CADASTRO DE DIRETOR");

        jLabel6.setText("Nome");

        btCadDir.setText("Cadastrar");

        jLabel9.setText("CPF");

        javax.swing.GroupLayout jPanelCadDiretorLayout = new javax.swing.GroupLayout(jPanelCadDiretor);
        jPanelCadDiretor.setLayout(jPanelCadDiretorLayout);
        jPanelCadDiretorLayout.setHorizontalGroup(
            jPanelCadDiretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretorLayout.createSequentialGroup()
                .addGroup(jPanelCadDiretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadDiretorLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanelCadDiretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelCadDiretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cxNomeDirCad, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(cxCpfDirCad)))
                    .addGroup(jPanelCadDiretorLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel5)))
                .addContainerGap(330, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadDiretorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btCadDir)
                .addGap(177, 177, 177))
        );
        jPanelCadDiretorLayout.setVerticalGroup(
            jPanelCadDiretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretorLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addGap(89, 89, 89)
                .addGroup(jPanelCadDiretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cxNomeDirCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadDiretorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cxCpfDirCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(btCadDir)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jScrollPaneDiretorCad.setViewportView(jPanelCadDiretor);

        jTabbedPaneCadastro.addTab("Diretor", jScrollPaneDiretorCad);

        jLabel2.setText("Nome");

        jLabel4.setText("CADASTRO DE PROFESSOR");

        btCadProf.setText("Cadastrar");

        jLabel8.setText("CPF");

        jLabel21.setText("Disciplina");

        javax.swing.GroupLayout jPanelCadProfessorLayout = new javax.swing.GroupLayout(jPanelCadProfessor);
        jPanelCadProfessor.setLayout(jPanelCadProfessorLayout);
        jPanelCadProfessorLayout.setHorizontalGroup(
            jPanelCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadProfessorLayout.createSequentialGroup()
                .addGroup(jPanelCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadProfessorLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanelCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadProfessorLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(23, 23, 23)
                                .addComponent(cxDisciplinaProfCad, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                            .addGroup(jPanelCadProfessorLayout.createSequentialGroup()
                                .addGroup(jPanelCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addGap(41, 41, 41)
                                .addGroup(jPanelCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cxNomeProfCad, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(cxCpfProfCad)))))
                    .addGroup(jPanelCadProfessorLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel4)))
                .addContainerGap(292, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadProfessorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btCadProf)
                .addGap(149, 149, 149))
        );
        jPanelCadProfessorLayout.setVerticalGroup(
            jPanelCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadProfessorLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel4)
                .addGap(85, 85, 85)
                .addGroup(jPanelCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cxNomeProfCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cxCpfProfCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cxDisciplinaProfCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btCadProf)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jScrollPaneProfessorCad.setViewportView(jPanelCadProfessor);

        jTabbedPaneCadastro.addTab("Professor", jScrollPaneProfessorCad);

        jLabel10.setText("CADASTRO DE ALUNO");

        jLabel11.setText("Nome");

        jLabel13.setText("RA");

        btCadAluno.setText("Cadastrar");

        jLabel22.setText("Turma");

        javax.swing.GroupLayout jPanelAlunoLayout = new javax.swing.GroupLayout(jPanelAluno);
        jPanelAluno.setLayout(jPanelAlunoLayout);
        jPanelAlunoLayout.setHorizontalGroup(
            jPanelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlunoLayout.createSequentialGroup()
                .addGroup(jPanelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAlunoLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(23, 23, 23)
                                .addComponent(cxTurmaAlunoCad1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                            .addGroup(jPanelAlunoLayout.createSequentialGroup()
                                .addGroup(jPanelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addGap(23, 23, 23)
                                .addGroup(jPanelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cxNomeAlunoCad, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(cxRaAlunoCad)))))
                    .addGroup(jPanelAlunoLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel10)))
                .addGap(330, 330, 330))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlunoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btCadAluno)
                .addGap(179, 179, 179))
        );
        jPanelAlunoLayout.setVerticalGroup(
            jPanelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlunoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel10)
                .addGap(80, 80, 80)
                .addGroup(jPanelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cxNomeAlunoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cxRaAlunoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cxTurmaAlunoCad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btCadAluno)
                .addGap(69, 69, 69))
        );

        jScrollPaneAlunoCad.setViewportView(jPanelAluno);

        jTabbedPaneCadastro.addTab("Aluno", jScrollPaneAlunoCad);

        jScrollPaneCadastro.setViewportView(jTabbedPaneCadastro);

        jTabbedPane1.addTab("Cadastro", jScrollPaneCadastro);

        jLabel7.setText("CONSULTA DE DIRETOR");

        cxNomeDirCons.setBackground(new java.awt.Color(255, 255, 255));
        cxNomeDirCons.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Nome");

        btConsDir.setText("Consultar");

        jLabel14.setText("CPF");

        btAlterarDir.setText("Alterar");

        btDeletarDir.setText("Deletar");

        btListarDir.setText("Listar Diretores");

        javax.swing.GroupLayout jPanelCadDiretor1Layout = new javax.swing.GroupLayout(jPanelCadDiretor1);
        jPanelCadDiretor1.setLayout(jPanelCadDiretor1Layout);
        jPanelCadDiretor1Layout.setHorizontalGroup(
            jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel7))
                    .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cxNomeDirCons, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(cxCpfDirCons)))
                    .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btListarDir)
                        .addGap(18, 18, 18)
                        .addComponent(btConsDir)
                        .addGap(18, 18, 18)
                        .addComponent(btAlterarDir)
                        .addGap(18, 18, 18)
                        .addComponent(btDeletarDir)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanelCadDiretor1Layout.setVerticalGroup(
            jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel7)
                .addGap(117, 117, 117)
                .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cxNomeDirCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(cxCpfDirCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsDir)
                    .addComponent(btAlterarDir)
                    .addComponent(btDeletarDir)
                    .addComponent(btListarDir))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jScrollPaneDiretorCons.setViewportView(jPanelCadDiretor1);

        jTabbedPane2.addTab("Diretor", jScrollPaneDiretorCons);

        jLabel15.setText("CONSULTA DE ALUNO");

        cxNomeProfessorCons.setBackground(new java.awt.Color(255, 255, 255));
        cxNomeProfessorCons.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jLabel16.setText("Nome");

        btConsProfessor.setText("Consultar");

        jLabel17.setText("CPF");

        cxCpfProfessorCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCpfProfessorConsActionPerformed(evt);
            }
        });

        btAlterarProfessor.setText("Alterar");

        btDeletarProfessor.setText("Deletar");

        btListarProfessor.setText("Listar Professores");

        jLabel3.setText("Disciplina");

        javax.swing.GroupLayout jPanelCadDiretor2Layout = new javax.swing.GroupLayout(jPanelCadDiretor2);
        jPanelCadDiretor2.setLayout(jPanelCadDiretor2Layout);
        jPanelCadDiretor2Layout.setHorizontalGroup(
            jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(cxNomeProfessorCons, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cxDisciplinaProfessorCons))
                            .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cxCpfProfessorCons, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btListarProfessor)
                        .addGap(18, 18, 18)
                        .addComponent(btConsProfessor)
                        .addGap(18, 18, 18)
                        .addComponent(btAlterarProfessor)
                        .addGap(18, 18, 18)
                        .addComponent(btDeletarProfessor))
                    .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel15)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanelCadDiretor2Layout.setVerticalGroup(
            jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel15)
                .addGap(117, 117, 117)
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cxNomeProfessorCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxDisciplinaProfessorCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cxCpfProfessorCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsProfessor)
                    .addComponent(btAlterarProfessor)
                    .addComponent(btDeletarProfessor)
                    .addComponent(btListarProfessor))
                .addGap(77, 77, 77))
        );

        jScrollPaneProfessorCons.setViewportView(jPanelCadDiretor2);

        jTabbedPane2.addTab("Professor", jScrollPaneProfessorCons);

        jLabel18.setText("CONSULTA DE DIRETOR");

        cxNomeAlunoCons.setBackground(new java.awt.Color(255, 255, 255));
        cxNomeAlunoCons.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jLabel19.setText("Nome");

        btConsAluno.setText("Consultar");

        jLabel20.setText("RA");

        cxRaAlunoCons.setBackground(new java.awt.Color(255, 255, 255));

        btAlterarAluno.setText("Alterar");

        btDeletarAluno.setText("Deletar");

        btListarAlunos.setText("Listar Alunos");

        jLabel23.setText("Turma");

        cxTurmaAlunoCons.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelCadDiretor3Layout = new javax.swing.GroupLayout(jPanelCadDiretor3);
        jPanelCadDiretor3.setLayout(jPanelCadDiretor3Layout);
        jPanelCadDiretor3Layout.setHorizontalGroup(
            jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel18))
                    .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addGap(28, 28, 28)
                                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cxNomeAlunoCons, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addComponent(cxRaAlunoCons)))
                            .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(27, 27, 27)
                                .addComponent(cxTurmaAlunoCons))))
                    .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btListarAlunos)
                        .addGap(18, 18, 18)
                        .addComponent(btConsAluno)
                        .addGap(18, 18, 18)
                        .addComponent(btAlterarAluno)
                        .addGap(18, 18, 18)
                        .addComponent(btDeletarAluno)))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        jPanelCadDiretor3Layout.setVerticalGroup(
            jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel18)
                .addGap(117, 117, 117)
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cxNomeAlunoCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxTurmaAlunoCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(cxRaAlunoCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsAluno)
                    .addComponent(btAlterarAluno)
                    .addComponent(btDeletarAluno)
                    .addComponent(btListarAlunos))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jScrollPaneAlunoCons.setViewportView(jPanelCadDiretor3);

        jTabbedPane2.addTab("Aluno", jScrollPaneAlunoCons);

        jScrollPaneConsulta.setViewportView(jTabbedPane2);

        jTabbedPane1.addTab("Consulta", jScrollPaneConsulta);

        jPanel1.add(jTabbedPane1);

        getContentPane().add(jPanel1);

        Iniciar.setText("Iniciar");

        jMenuItemAbrir.setText("Abrir");
        Iniciar.add(jMenuItemAbrir);

        jMenuItemSalvar.setText("Salvar");
        Iniciar.add(jMenuItemSalvar);

        jMenuItemSair.setText("Sair");
        Iniciar.add(jMenuItemSair);

        jMenuBar1.add(Iniciar);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(700, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cxCpfProfessorConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCpfProfessorConsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCpfProfessorConsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Iniciar;
    private javax.swing.JButton btAlterarAluno;
    private javax.swing.JButton btAlterarDir;
    private javax.swing.JButton btAlterarProfessor;
    private javax.swing.JButton btCadAluno;
    private javax.swing.JButton btCadDir;
    private javax.swing.JButton btCadProf;
    private javax.swing.JButton btConsAluno;
    private javax.swing.JButton btConsDir;
    private javax.swing.JButton btConsProfessor;
    private javax.swing.JButton btDeletarAluno;
    private javax.swing.JButton btDeletarDir;
    private javax.swing.JButton btDeletarProfessor;
    private javax.swing.JButton btListarAlunos;
    private javax.swing.JButton btListarDir;
    private javax.swing.JButton btListarProfessor;
    private javax.swing.JTextField cxCpfDirCad;
    private javax.swing.JTextField cxCpfDirCons;
    private javax.swing.JTextField cxCpfProfCad;
    private javax.swing.JTextField cxCpfProfessorCons;
    private javax.swing.JTextField cxDisciplinaProfCad;
    private javax.swing.JTextField cxDisciplinaProfessorCons;
    private javax.swing.JTextField cxNomeAlunoCad;
    private javax.swing.JTextField cxNomeAlunoCons;
    private javax.swing.JTextField cxNomeDirCad;
    private javax.swing.JTextField cxNomeDirCons;
    private javax.swing.JTextField cxNomeProfCad;
    private javax.swing.JTextField cxNomeProfessorCons;
    private javax.swing.JTextField cxRaAlunoCad;
    private javax.swing.JTextField cxRaAlunoCons;
    private javax.swing.JTextField cxTurmaAlunoCad1;
    private javax.swing.JTextField cxTurmaAlunoCons;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAluno;
    private javax.swing.JPanel jPanelCadDiretor;
    private javax.swing.JPanel jPanelCadDiretor1;
    private javax.swing.JPanel jPanelCadDiretor2;
    private javax.swing.JPanel jPanelCadDiretor3;
    private javax.swing.JPanel jPanelCadProfessor;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPaneAlunoCad;
    private javax.swing.JScrollPane jScrollPaneAlunoCons;
    private javax.swing.JScrollPane jScrollPaneCadastro;
    private javax.swing.JScrollPane jScrollPaneConsulta;
    private javax.swing.JScrollPane jScrollPaneDiretorCad;
    private javax.swing.JScrollPane jScrollPaneDiretorCons;
    private javax.swing.JScrollPane jScrollPanePrincipal;
    private javax.swing.JScrollPane jScrollPaneProfessorCad;
    private javax.swing.JScrollPane jScrollPaneProfessorCons;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPaneCadastro;
    // End of variables declaration//GEN-END:variables
}
