/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.*;
import java.util.function.Function;

import javax.swing.JOptionPane;
import model.Aluno;
import model.Diretor;
import model.Professor;

/**
 *
 * @author Jean
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    ControllerArquivoTextoPessoaGeral<Aluno> controllerAluno = new ControllerArquivoTextoPessoaGeral();
    ControllerArquivoTextoPessoaGeral<Professor> CP = new ControllerArquivoTextoPessoaGeral();
    ControllerArquivoTextoPessoaGeral<Diretor> CD = new ControllerArquivoTextoPessoaGeral();
    
    Function funcAlunos<StringTokenizer, T> = (token -> {
            Aluno pessoa = new Aluno();
            pessoa.setIdPessoa(Integer.parseInt((token.nextToken())));
            pessoa.setNome(token.nextToken());
            pessoa.setTurma(token.nextToken());
            return pessoa;});
    
    
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPanePrincipal = new javax.swing.JScrollPane();
        jPanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPaneCRUD = new javax.swing.JScrollPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPaneDiretorCons = new javax.swing.JScrollPane();
        jPanelCadDiretor1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cxNomeDir = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btConsDir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cxCpfDir = new javax.swing.JTextField();
        btAlterarDir = new javax.swing.JButton();
        btDeletarDir = new javax.swing.JButton();
        btListarDir = new javax.swing.JButton();
        btCadDir = new javax.swing.JButton();
        cxIdDir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPaneProfessorCons = new javax.swing.JScrollPane();
        jPanelCadDiretor2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cxNomeProfessor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btConsProfessor = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cxCpfProfessor = new javax.swing.JTextField();
        btAlterarProfessor = new javax.swing.JButton();
        btDeletarProfessor = new javax.swing.JButton();
        btListarProfessor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cxDisciplinaProfessor = new javax.swing.JTextField();
        brCadProfessor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cxIdProfessor = new javax.swing.JTextField();
        jScrollPaneAlunoCons = new javax.swing.JScrollPane();
        jPanelCadDiretor3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        cxNomeAlunoCons = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btConsAluno = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        cxIdAlunoCons = new javax.swing.JTextField();
        btAlterarAluno = new javax.swing.JButton();
        btDeletarAluno = new javax.swing.JButton();
        btListarAlunos = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        cxTurmaAlunoCons = new javax.swing.JTextField();
        jButtonCadAluno = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Iniciar = new javax.swing.JMenu();
        jMenuAbrir = new javax.swing.JMenu();
        jMenuItemAbrirDiretor = new javax.swing.JMenuItem();
        jMenuItemAbrirProfessor = new javax.swing.JMenuItem();
        jMenuItemAbrirAluno = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 153));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jScrollPanePrincipal.setBackground(new java.awt.Color(255, 102, 102));

        jPanelPrincipal.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GERENCIADOR  ESCOLA UNITED");
        jPanelPrincipal.add(jLabel1);

        jScrollPanePrincipal.setViewportView(jPanelPrincipal);

        jTabbedPane1.addTab("Principal", jScrollPanePrincipal);

        jLabel7.setText("CONSULTA DE DIRETOR");

        cxNomeDir.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Nome");

        btConsDir.setText("Consultar");
        btConsDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsDirActionPerformed(evt);
            }
        });

        jLabel14.setText("CPF");

        btAlterarDir.setText("Alterar");
        btAlterarDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarDirActionPerformed(evt);
            }
        });

        btDeletarDir.setText("Deletar");
        btDeletarDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarDirActionPerformed(evt);
            }
        });

        btListarDir.setText("Listar Diretores");
        btListarDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarDirActionPerformed(evt);
            }
        });

        btCadDir.setText("Cadastrar");
        btCadDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadDirActionPerformed(evt);
            }
        });

        jLabel4.setText("ID");

        javax.swing.GroupLayout jPanelCadDiretor1Layout = new javax.swing.GroupLayout(jPanelCadDiretor1);
        jPanelCadDiretor1.setLayout(jPanelCadDiretor1Layout);
        jPanelCadDiretor1Layout.setHorizontalGroup(
            jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel7))
                    .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel4))
                        .addGap(19, 19, 19)
                        .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cxIdDir)
                            .addComponent(cxNomeDir, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(cxCpfDir)))
                    .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btListarDir)
                        .addGap(29, 29, 29)
                        .addComponent(btConsDir)
                        .addGap(32, 32, 32)
                        .addComponent(btAlterarDir)
                        .addGap(32, 32, 32)
                        .addComponent(btDeletarDir)
                        .addGap(28, 28, 28)
                        .addComponent(btCadDir)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanelCadDiretor1Layout.setVerticalGroup(
            jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel7)
                .addGap(117, 117, 117)
                .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadDiretor1Layout.createSequentialGroup()
                        .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cxNomeDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(cxCpfDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxIdDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(52, 52, 52)
                .addGroup(jPanelCadDiretor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btListarDir)
                    .addComponent(btConsDir)
                    .addComponent(btAlterarDir)
                    .addComponent(btDeletarDir)
                    .addComponent(btCadDir))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jScrollPaneDiretorCons.setViewportView(jPanelCadDiretor1);

        jTabbedPane2.addTab("Diretor", jScrollPaneDiretorCons);

        jLabel15.setText("CONSULTA DE PROFESSOR");

        cxNomeProfessor.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jLabel16.setText("Nome");

        btConsProfessor.setText("Consultar");
        btConsProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsProfessorActionPerformed(evt);
            }
        });

        jLabel17.setText("CPF");

        cxCpfProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCpfProfessorActionPerformed(evt);
            }
        });

        btAlterarProfessor.setText("Alterar");
        btAlterarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarProfessorActionPerformed(evt);
            }
        });

        btDeletarProfessor.setText("Deletar");
        btDeletarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarProfessorActionPerformed(evt);
            }
        });

        btListarProfessor.setText("Listar Professores");
        btListarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarProfessorActionPerformed(evt);
            }
        });

        jLabel3.setText("Disciplina");

        brCadProfessor.setText("Cadastrar");
        brCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brCadProfessorActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        javax.swing.GroupLayout jPanelCadDiretor2Layout = new javax.swing.GroupLayout(jPanelCadDiretor2);
        jPanelCadDiretor2.setLayout(jPanelCadDiretor2Layout);
        jPanelCadDiretor2Layout.setHorizontalGroup(
            jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel15))
                    .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                        .addComponent(cxNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(cxDisciplinaProfessor))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadDiretor2Layout.createSequentialGroup()
                                        .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cxCpfProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cxIdProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadDiretor2Layout.createSequentialGroup()
                                .addComponent(btListarProfessor)
                                .addGap(18, 18, 18)
                                .addComponent(btConsProfessor)
                                .addGap(18, 18, 18)
                                .addComponent(btAlterarProfessor)
                                .addGap(18, 18, 18)
                                .addComponent(btDeletarProfessor)
                                .addGap(29, 29, 29)
                                .addComponent(brCadProfessor)))))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanelCadDiretor2Layout.setVerticalGroup(
            jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel15)
                .addGap(73, 73, 73)
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cxNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxDisciplinaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cxCpfProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cxIdProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanelCadDiretor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brCadProfessor)
                    .addComponent(btDeletarProfessor)
                    .addComponent(btListarProfessor)
                    .addComponent(btConsProfessor)
                    .addComponent(btAlterarProfessor))
                .addGap(85, 85, 85))
        );

        jScrollPaneProfessorCons.setViewportView(jPanelCadDiretor2);

        jTabbedPane2.addTab("Professor", jScrollPaneProfessorCons);

        jLabel18.setText("CONSULTA DE ALUNO");

        cxNomeAlunoCons.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        jLabel19.setText("Nome");

        btConsAluno.setText("Consultar");
        btConsAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsAlunoActionPerformed(evt);
            }
        });

        jLabel20.setText("ID");

        btAlterarAluno.setText("Alterar");
        btAlterarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarAlunoActionPerformed(evt);
            }
        });

        btDeletarAluno.setText("Deletar");
        btDeletarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarAlunoActionPerformed(evt);
            }
        });

        btListarAlunos.setText("Listar Alunos");
        btListarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarAlunosActionPerformed(evt);
            }
        });

        jLabel23.setText("Turma");

        jButtonCadAluno.setText("Cadastrar");
        jButtonCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadDiretor3Layout = new javax.swing.GroupLayout(jPanelCadDiretor3);
        jPanelCadDiretor3.setLayout(jPanelCadDiretor3Layout);
        jPanelCadDiretor3Layout.setHorizontalGroup(
            jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel18))
                    .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addGap(28, 28, 28)
                                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cxNomeAlunoCons, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addComponent(cxIdAlunoCons)))
                            .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(27, 27, 27)
                                .addComponent(cxTurmaAlunoCons))))
                    .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btListarAlunos)
                        .addGap(32, 32, 32)
                        .addComponent(btConsAluno)
                        .addGap(28, 28, 28)
                        .addComponent(btAlterarAluno)
                        .addGap(43, 43, 43)
                        .addComponent(btDeletarAluno)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCadAluno)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanelCadDiretor3Layout.setVerticalGroup(
            jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadDiretor3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel18)
                .addGap(117, 117, 117)
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cxNomeAlunoCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxTurmaAlunoCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(cxIdAlunoCons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanelCadDiretor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsAluno)
                    .addComponent(btAlterarAluno)
                    .addComponent(btDeletarAluno)
                    .addComponent(btListarAlunos)
                    .addComponent(jButtonCadAluno))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jScrollPaneAlunoCons.setViewportView(jPanelCadDiretor3);

        jTabbedPane2.addTab("Aluno", jScrollPaneAlunoCons);

        jScrollPaneCRUD.setViewportView(jTabbedPane2);

        jTabbedPane1.addTab("CRUD", jScrollPaneCRUD);

        jPanel1.add(jTabbedPane1);

        getContentPane().add(jPanel1);

        Iniciar.setText("Iniciar");

        jMenuAbrir.setText("Abrir");

        jMenuItemAbrirDiretor.setText("Abrir Diretores");
        jMenuItemAbrirDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirDiretorActionPerformed(evt);
            }
        });
        jMenuAbrir.add(jMenuItemAbrirDiretor);

        jMenuItemAbrirProfessor.setText("Abrir Professores");
        jMenuItemAbrirProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirProfessorActionPerformed(evt);
            }
        });
        jMenuAbrir.add(jMenuItemAbrirProfessor);

        jMenuItemAbrirAluno.setText("Abrir Alunos");
        jMenuItemAbrirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirAlunoActionPerformed(evt);
            }
        });
        jMenuAbrir.add(jMenuItemAbrirAluno);

        Iniciar.add(jMenuAbrir);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        Iniciar.add(jMenuItemSair);

        jMenuBar1.add(Iniciar);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(710, 523));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAbrirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirAlunoActionPerformed

        controllerAluno.lerPessoas();

    }//GEN-LAST:event_jMenuItemAbrirAlunoActionPerformed

    private void jMenuItemAbrirProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirProfessorActionPerformed
        CP.lerProfessores();
    }//GEN-LAST:event_jMenuItemAbrirProfessorActionPerformed

    private void jMenuItemAbrirDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirDiretorActionPerformed
        CD.lerDiretores();
    }//GEN-LAST:event_jMenuItemAbrirDiretorActionPerformed

    private void btListarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarAlunosActionPerformed
        verificacaoListaAluno();
        JOptionPane.showMessageDialog(null, controllerAluno.getListAluno(), "Lista de Alunos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btListarAlunosActionPerformed

    private void btDeletarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarAlunoActionPerformed
        verificacaoListaAluno();
        controllerAluno.setAluno(new Aluno(Integer.parseInt(cxIdAlunoCons.getText())));
        if (controllerAluno.delete()) {
            JOptionPane.showMessageDialog(null, "Deletado", "Deletar", 1);
            limparConsAluno();
        } else {
            JOptionPane.showMessageDialog(null, "ERROR", "Deletar", 0);
        }
    }//GEN-LAST:event_btDeletarAlunoActionPerformed

    private void btAlterarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarAlunoActionPerformed
        verificacaoListaAluno();

        if (controllerAluno.updateAluno(Integer.parseInt(cxIdAlunoCons.getText()), cxNomeAlunoCons.getText(), cxTurmaAlunoCons.getText()) == 1) {
            JOptionPane.showMessageDialog(null, "Atualizado", "Atualizacao", 1);
        } else {
            JOptionPane.showMessageDialog(null, "Error", "Atualizacao", 0);
        }

    }//GEN-LAST:event_btAlterarAlunoActionPerformed

    private void btConsAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsAlunoActionPerformed
        verificacaoListaAluno();
        Aluno aluno = new Aluno(Integer.parseInt(cxIdAlunoCons.getText()));
        controllerAluno.setAluno(aluno);
        aluno = controllerAluno.consAluno();
        if (aluno != null) {
            cxNomeAlunoCons.setText(aluno.getNome());
            cxTurmaAlunoCons.setText(aluno.getTurma());
        } else {
            JOptionPane.showMessageDialog(null, "Não Encontrado", "ERROR", 0);
            limparConsAluno();
        }
    }//GEN-LAST:event_btConsAlunoActionPerformed

    private void cxCpfProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCpfProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCpfProfessorActionPerformed

    private void jButtonCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadAlunoActionPerformed
        verificacaoListaAluno();
        if (cxNomeAlunoCons.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ERROR", "ERROR", 0);
        } else {
            controllerAluno.setAluno(new Aluno(cxNomeAlunoCons.getText(), cxTurmaAlunoCons.getText()));
            controllerAluno.gravarAluno();
            JOptionPane.showMessageDialog(null, "Cadastrado!", "Cadastro", 1);

        }
    }//GEN-LAST:event_jButtonCadAlunoActionPerformed

    private void brCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brCadProfessorActionPerformed
        verificacaoListaProfessor();
        if (cxNomeProfessor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ERROR", "ERROR", 0);
        } else {
            CP.setProfessor(new Professor(cxNomeProfessor.getText(), cxDisciplinaProfessor.getText(), Integer.parseInt(cxCpfProfessor.getText())));
            CP.gravarProfessor();
            JOptionPane.showMessageDialog(null, "Cadastrado!", "Cadastro", 1);
        }
    }//GEN-LAST:event_brCadProfessorActionPerformed

    private void btConsProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsProfessorActionPerformed
        verificacaoListaProfessor();
        Professor professor = new Professor(Integer.parseInt(cxIdProfessor.getText()));
        CP.setProfessor(professor);
        professor = CP.consProfessor();
        if (professor != null) {
            cxNomeProfessor.setText(professor.getNome());
            cxDisciplinaProfessor.setText(professor.getDisciplina());
            cxCpfProfessor.setText(professor.getCpf().toString());
        } else {
            JOptionPane.showMessageDialog(null, "Não Encontrado", "ERROR", 0);
            limparConsAluno();
        }
    }//GEN-LAST:event_btConsProfessorActionPerformed

    private void btAlterarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarProfessorActionPerformed
        verificacaoListaProfessor();

        if (CP.updateProfessor(Integer.parseInt(cxIdProfessor.getText()), cxNomeProfessor.getText(), cxDisciplinaProfessor.getText(), Integer.parseInt(cxCpfProfessor.getText())) == 1) {
            JOptionPane.showMessageDialog(null, "Atualizado", "Atualizacao", 1);
        } else {
            JOptionPane.showMessageDialog(null, "Error", "Atualizacao", 0);
        }
    }//GEN-LAST:event_btAlterarProfessorActionPerformed

    private void btDeletarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarProfessorActionPerformed
        verificacaoListaProfessor();
        CP.setProfessor(new Professor(Integer.parseInt(cxIdProfessor.getText())));
        if (CP.delete()) {
            JOptionPane.showMessageDialog(null, "Deletado", "Deletar", 1);
            limparConsProfessor();
        } else {
            JOptionPane.showMessageDialog(null, "ERROR", "Deletar", 0);
        }
    }//GEN-LAST:event_btDeletarProfessorActionPerformed

    private void btListarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarProfessorActionPerformed
        verificacaoListaProfessor();
        JOptionPane.showMessageDialog(null, CP.getListProfessor(), "Lista de Professores", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btListarProfessorActionPerformed

    private void btListarDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarDirActionPerformed
        verificacaoListaDiretor();
        JOptionPane.showMessageDialog(null, CD.getListDiretor(), "Lista de Diretores", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btListarDirActionPerformed

    private void btConsDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsDirActionPerformed
        verificacaoListaDiretor();
        Diretor diretor = new Diretor(Integer.parseInt(cxIdDir.getText()));
        CD.setDiretor(diretor);
        diretor = CD.consDiretor();
        if (diretor != null) {
            cxNomeDir.setText(diretor.getNome());
            cxCpfDir.setText(diretor.getCpf().toString());
        } else {
            JOptionPane.showMessageDialog(null, "Não Encontrado", "ERROR", 0);
            limparConsDiretor();
        }
    }//GEN-LAST:event_btConsDirActionPerformed

    private void btAlterarDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarDirActionPerformed
        verificacaoListaDiretor();

        if (CD.updateDiretor(Integer.parseInt(cxIdDir.getText()),
                cxNomeDir.getText(),
                Integer.parseInt(cxCpfDir.getText())) == 1) {
            JOptionPane.showMessageDialog(null, "Atualizado", "Atualizacao", 1);
        } else {
            JOptionPane.showMessageDialog(null, "Error", "Atualizacao", 0);
        }
    }//GEN-LAST:event_btAlterarDirActionPerformed

    private void btDeletarDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarDirActionPerformed
        verificacaoListaDiretor();
        CD.setDiretor(new Diretor(Integer.parseInt(cxIdDir.getText())));
        if (CD.delete()) {
            JOptionPane.showMessageDialog(null, "Deletado", "Deletar", 1);
            limparConsDiretor();
        } else {
            JOptionPane.showMessageDialog(null, "ERROR", "Deletar", 0);
        }
    }//GEN-LAST:event_btDeletarDirActionPerformed

    private void btCadDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadDirActionPerformed
        verificacaoListaDiretor();
        if (cxNomeDir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ERROR", "ERROR", 0);
        } else {
            CD.setDiretor(new Diretor(cxNomeDir.getText(), Integer.parseInt(cxCpfDir.getText())));
            CD.gravarDiretor();
            JOptionPane.showMessageDialog(null, "Cadastrado!", "Cadastro", 1);
        }
    }//GEN-LAST:event_btCadDirActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    public void verificacaoListaAluno() {
        if (controllerAluno.getArquivo() == null) {
            controllerAluno.lerAlunos();

        }
    }

    public void verificacaoListaProfessor() {
        if (CP.getArquivo() == null) {
            CP.lerProfessores();
        }
    }

    public void verificacaoListaDiretor() {
        if (CD.getArquivo() == null) {
            CD.lerDiretores();
        }

    }

    public void limparConsAluno() {
        cxNomeAlunoCons.setText("");
        cxTurmaAlunoCons.setText("");
        cxIdAlunoCons.setText("");
    }

    public void limparConsProfessor() {
        cxNomeProfessor.setText("");
        cxCpfProfessor.setText("");
        cxDisciplinaProfessor.setText("");
        cxIdProfessor.setText("");
    }

    public void limparConsDiretor() {
        cxNomeDir.setText("");
        cxCpfDir.setText("");
        cxIdDir.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Iniciar;
    private javax.swing.JButton brCadProfessor;
    private javax.swing.JButton btAlterarAluno;
    private javax.swing.JButton btAlterarDir;
    private javax.swing.JButton btAlterarProfessor;
    private javax.swing.JButton btCadDir;
    private javax.swing.JButton btConsAluno;
    private javax.swing.JButton btConsDir;
    private javax.swing.JButton btConsProfessor;
    private javax.swing.JButton btDeletarAluno;
    private javax.swing.JButton btDeletarDir;
    private javax.swing.JButton btDeletarProfessor;
    private javax.swing.JButton btListarAlunos;
    private javax.swing.JButton btListarDir;
    private javax.swing.JButton btListarProfessor;
    private javax.swing.JTextField cxCpfDir;
    private javax.swing.JTextField cxCpfProfessor;
    private javax.swing.JTextField cxDisciplinaProfessor;
    private javax.swing.JTextField cxIdAlunoCons;
    private javax.swing.JTextField cxIdDir;
    private javax.swing.JTextField cxIdProfessor;
    private javax.swing.JTextField cxNomeAlunoCons;
    private javax.swing.JTextField cxNomeDir;
    private javax.swing.JTextField cxNomeProfessor;
    private javax.swing.JTextField cxTurmaAlunoCons;
    private javax.swing.JButton jButtonCadAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenuAbrir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbrirAluno;
    private javax.swing.JMenuItem jMenuItemAbrirDiretor;
    private javax.swing.JMenuItem jMenuItemAbrirProfessor;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCadDiretor1;
    private javax.swing.JPanel jPanelCadDiretor2;
    private javax.swing.JPanel jPanelCadDiretor3;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPaneAlunoCons;
    private javax.swing.JScrollPane jScrollPaneCRUD;
    private javax.swing.JScrollPane jScrollPaneDiretorCons;
    private javax.swing.JScrollPane jScrollPanePrincipal;
    private javax.swing.JScrollPane jScrollPaneProfessorCons;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
